pipeline {
    agent {
        docker {
            image 'jibin321/maven-docker-agent:v2'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                sh 'echo passed'
                // git branch: 'main', url: 'https://github.com/user/repo.git'
            }
        }

        stage('Build and Test') {
            steps {
                sh 'ls -ltr'
                sh 'cd spring-boot-app && mvn clean package'
            }
        }

              stage('SonarQube Analysis') {
                steps {
                  withSonarQubeEnv('sonarqube') {
                      sh '''
                          cd spring-boot-app
                          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar \
                            -Dsonar.projectKey=my-ec2-project \
                            -Dsonar.projectName="Spring Boot App" \
                            -Dsonar.host.url=$SONAR_HOST_URL
                      '''
                  }
              }
          }

        stage('Build and Push Docker Image') {
            environment {
                DOCKER_IMAGE = "ajilash25/spring-boot-app:${BUILD_NUMBER}"
                REGISTRY_CREDENTIALS = credentials('docker-cred')
            }

            steps {
                script {
                    sh 'cd spring-boot-app && docker build -t ${DOCKER_IMAGE} .'

                    def dockerImage = docker.image("${DOCKER_IMAGE}")

                    docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                        dockerImage.push()
                        dockerImage.push("latest")
                    }
                }
            }
        }

        stage('Update Deployment File') {
            environment {
                GIT_REPO_NAME = "java-maven-sonar-argocd"
                GIT_USER_NAME = "Ajilash25"
            }

            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'github-id',
                        usernameVariable: 'GITHUB_USERNAME',
                        passwordVariable: 'GITHUB_TOKEN'
                    )
                ]) {
                    sh '''
                        git config --global --add safe.directory "${WORKSPACE}"
                        git config --global user.email "ajilashedward25@gmail.com"
                        git config --global user.name "Ajilash25"
                        sed -i "s|image: ajilash25/spring-boot-app:.*|image: ajilash25/spring-boot-app:${BUILD_NUMBER}|g" spring-boot-app-manifests/deployment.yml
                        git -c safe.directory="${WORKSPACE}" add spring-boot-app-manifests/deployment.yml
                        git commit -m "Update Java Maven image to ${BUILD_NUMBER}" || echo "No changes to commit"
                        git push https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                    '''
                }
            }
        }
    }
}
