pipeline {
agent {
docker {
image 'jibin321/maven-docker-agent\:v2'
args '--user root -v /var/run/docker.sock:/var/run/docker.sock' 
}
}
stage('Checkout') {
    steps {
        checkout scm
    }
}
```
stage('Build and Test') {
steps {
    dir('spring-boot-app') {
        sh 'ls -la'
        sh 'mvn clean package'
    }
}
```

}
stage('SonarQube Analysis') {
steps {
withSonarQubeEnv('sonarqube') {
sh 'mvn org.sonarsource.scanner.maven\:sonar-maven-plugin\:sonar -Dsonar.projectKey=my-ec2-project'
}
}
}
stage('Build and Push Docker Image') {
environment {
DOCKER\_IMAGE = "ajilash25/spring-boot-app:${BUILD\_NUMBER}"
REGISTRY\_CREDENTIALS = credentials('docker-cred')
}

```
steps {
    dir('spring-boot-app') {
        sh 'docker build -t $DOCKER_IMAGE .'

        sh 'echo $REGISTRY_CREDENTIALS_PSW | docker login -u $REGISTRY_CREDENTIALS_USR --password-stdin'

        sh 'docker push $DOCKER_IMAGE'
    }
}

}

stage('Update Deployment File') {
steps {
script {
withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB\_TOKEN')]) {
sh '''
cd "$WORKSPACE"

```
                git config user.email "ajilashedward25@gmail.com"
                git config user.name "Ajilash25"

                git status

                # Update your deployment YAML here
                # sed -i "s|image:.*|image: ajilash25/spring-boot-app:${BUILD_NUMBER}|" spring-boot-app-manifests/deployment.yml

                git add spring-boot-app-manifests/deployment.yml
                git commit -m "Update Docker image to ${BUILD_NUMBER}" || true

                git push https://${GITHUB_TOKEN}@github.com/ajilash25/java-maven-sonar-argocd.git HEAD:main
            '''
        }
    }
}

}
}
